# Generated by Django 2.2.17 on 2020-11-02 22:57

import colorfield.fields
import counter.settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=counter.settings.game_code_gen, max_length=5)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(choices=[('Red', '#e93b23'), ('Blue', '#256881'), ('Yellow', '#e9bd2c'), ('Green', '#196337'), ('Black', '#171207')], default='#FFFFFF', max_length=18)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Game')),
            ],
            options={
                'unique_together': {('name', 'color', 'game')},
            },
        ),
    ]
