# Generated by Django 2.2.17 on 2020-11-04 21:26

import counter.helpers.gen_game_code
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=counter.helpers.gen_game_code.generate, max_length=5)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('#e93b23', 'red'), ('#256881', 'blue'), ('#e9bd2c', 'yellow'),
                                                    ('#196337', 'green'), ('#171207', 'black')], max_length=7)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Game')),
            ],
            options={
                'unique_together': {('name', 'color', 'game')},
            },
        ),
    ]
