# Generated by Django 2.2.17 on 2020-11-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_train_cars', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'),
                                                              (4, 'four'), (5, 'five'), (6, 'six')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Player')),
            ],
        ),
    ]
